name: Generate Snake Animation

on:
  push:
    branches:
      - main  # Substitua "main" pela sua branch padrão, caso seja diferente
  schedule:
    - cron: "0 0 * * *"  # Executa o workflow diariamente
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: LoboProgrammingg
          outputs: dist/snake.svg

      - name: Push Snake Animation to Output Branch
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
